crawler={
    "timeOut":3,
    "threadsNum":10,
    "headers":{
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
    }
}

proxy_Ip={
    "wuyou":[
        "http://www.data5u.com/free/index.shtml",
        "http://www.data5u.com/free/gngn/index.shtml",
        "http://www.data5u.com/free/gnpt/index.shtml",
        "http://www.data5u.com/free/gwgn/index.shtml",
        "http://www.data5u.com/free/gwpt/index.shtml"
    ],
    "66":[
        "http://www.66ip.cn/"
    ],
    "xici":[
        "https://www.xicidaili.com/nn/",
        "https://www.xicidaili.com/nt/",
        "https://www.xicidaili.com/wn/",
        "https://www.xicidaili.com/wt/"
    ]
}
DATABASE={
    "host":"localhost",
    "port":3306,
    "database":"ipProxy",
    "username":"root",
    "password":"mahongying"
}
